### ISSUE TITLE
Problem with padding

### ISSUE THREAD

**Issue by pashok3d** [sdadas/polish-roberta#2]
I would like to use `RobertaForSequenceClassification`(huggingface) with your model, but I have a problem with padding. For BERT, I would use `tokenizer.encode_plus()` to deal with special tokens and padding. Here we have `SentencePieceBPETokenizer`, which doesn't have such method.
I tried to use `tokenizer.enable_padding(max_length = 64)` and after encoding I get smth like `[0, 50, 15,17, 20,11,2, 0, ... , 0]`. Though `tokenizer.token_to_id('<pad>')` = 1.
Also, when creating model object, i see that padding_idx=1.

```
RobertaForSequenceClassification( 
(roberta): RobertaModel(
(embeddings): RobertaEmbeddings(
(word_embeddings): Embedding(50001, 768, padding_idx=1)
(position_embeddings): Embedding(514, 768, padding_idx=1)
(token_type_embeddings): Embedding(1, 768)
(LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
(dropout): Dropout(p=0.1, inplace=False))
...
```
I don't know if there is a problem with it. 
According to the results, the model works fine and I got pretty good results.

p.s. I appriciate your work

**Comment by sdadas** [comment]
I'm not familiar with HuggingFace Transformers since both the model pre-training and all of our experiments were conducted on the Fairseq version of the model. However, I think you should use `enable_padding` with the following arguments to correctly pad sentences:
```python
tokenizer.enable_padding(pad_token="<pad>", pad_id=1, max_length=64)
```

**Comment by pashok3d** [comment]
Yes, it works now, thank you!
