### ISSUE TITLE
Transformers models

### ISSUE THREAD

**Issue by djstrong** [sdadas/polish-roberta#4]
There is a problem with the base model. In `vocab.json` an entry with id 50000 is missing.

In the large model a vocab size is 50009, but in `vocab.json` is no entry with id 50008 - however it does not cause errors.

**Comment by sdadas** [comment]
The vocabulary for the base model is indeed wrong. This is probably a bug in the conversion from Fairseq to Transformers. The last id in the vocab.json for the base model should be 49999, so the entry with id 50001 is unnecessary. Can you check whether removing the last entry from the vocab helps?

As for the difference in size of the model vocab and vocab.json file, Fairseq reserves the last entry in the vocabulary for a special `<mask>` symbol. This symbol should not be used in tasks other than language modeling so it was not included in the vocab.json and it is not included in the original Fairseq vocabulary as well.

**Comment by djstrong** [comment]
The error is appearing during training and not for every parameters (which is weird). I have added the 50000th entry and it helped.

I will check your solution.

**Comment by sdadas** [comment]
I uploaded the base model with modified `vocab.json` and `merges.txt` files. The issue should be fixed now.

**Comment by mczuk** [comment]
I can confirm, that the new model is working properly.
