### ISSUE TITLE
Problem with running example from README.md

### ISSUE THREAD

**Issue by lkotlewski** [sdadas/polish-roberta#6]
After downloading data using 
`python download_data.py` 
command and downloading and uzipping model to roberta_base_fairseq directory I tried to run 
`python run_tasks.py --arch roberta_base --model_dir roberta_base_fairseq --train-epochs 10 --tasks KLEJ-NKJP --fp16 True --max-sentences 8 --update-freq 2` 
command, but i got the following error: 

`File "/home/torales/.local/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 189, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: checkpoints/roberta_base_fairseq/KLEJ/NKJP-NER/checkpoint_best.pt`

Any ideas how can I fix it?

**Comment by sdadas** [comment]
`run_tasks.py` script includes three main steps: 

- Data pre-processing, which should produce `data_processed` directory
- Model training which should produce `checkpoints` directory with the fine-tuned model checkpoint
- Evaluation which uses the above checkpoint to assess the model performance

Your exception says that the checkpoint file does not exist. This suggests that the real error ocurred earlier, probably during the fine-tuning phase. Please search your logs for any previous errors. 

Running examples with our parameters requires a high end GPU. If your GPU doesn't support `fp16`, you should disable this option. If you have out of memory problems, you should reduce `max-sentences` (and optionally increase `update-freq` if you want to maintain the same batch size).

**Comment by lkotlewski** [comment]
Disabling `fp16` option resolved the problem. Thanks for quick response.
